name: Automated Testing CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  test:
    name: Run Test Suite
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint --if-present
        continue-on-error: true

      - name: Run unit tests
        run: npm run test:unit
        env:
          NODE_ENV: test
          JWT_SECRET: test-jwt-secret-key-ci
          JWT_REFRESH_SECRET: test-refresh-secret-key-ci

      - name: Run integration tests
        run: npm run test:integration
        env:
          NODE_ENV: test
          JWT_SECRET: test-jwt-secret-key-ci
          JWT_REFRESH_SECRET: test-refresh-secret-key-ci

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          NODE_ENV: test
          JWT_SECRET: test-jwt-secret-key-ci
          JWT_REFRESH_SECRET: test-refresh-secret-key-ci

      - name: Run security tests
        run: npm run test:security
        env:
          NODE_ENV: test
          JWT_SECRET: test-jwt-secret-key-ci
          JWT_REFRESH_SECRET: test-refresh-secret-key-ci

      - name: Run performance tests
        run: npm run test:performance
        env:
          NODE_ENV: test
          JWT_SECRET: test-jwt-secret-key-ci
          JWT_REFRESH_SECRET: test-refresh-secret-key-ci
        continue-on-error: true

      - name: Generate coverage report
        run: npm test -- --coverage
        env:
          NODE_ENV: test
          JWT_SECRET: test-jwt-secret-key-ci
          JWT_REFRESH_SECRET: test-refresh-secret-key-ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.node-version }}
          path: |
            coverage/
            test-results/

      - name: Archive coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-${{ matrix.node-version }}
          path: coverage/

  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint src/ --ext .js --max-warnings 0
        continue-on-error: true

      - name: Check code formatting
        run: npx prettier --check "src/**/*.js"
        continue-on-error: true

  security-scan:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run npm audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

      - name: Run Snyk security scan
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [test, code-quality]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build --if-present

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/

  notify:
    name: Notify Results
    runs-on: ubuntu-latest
    needs: [test, code-quality, security-scan, build]
    if: always()

    steps:
      - name: Send notification
        run: |
          echo "Test suite completed"
          echo "Test status: ${{ needs.test.result }}"
          echo "Code quality status: ${{ needs.code-quality.result }}"
          echo "Security scan status: ${{ needs.security-scan.result }}"
          echo "Build status: ${{ needs.build.result }}"
